import os
from typing import Any, Dict
from pathlib import Path
from functools import lru_cache

from dotenv import load_dotenv
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_neo4j import Neo4jGraph, GraphCypherQAChain
from langchain_core.prompts import PromptTemplate


# ---------------- ENV + PROMPTS (safe at import time) ----------------

CURRENT_DIR = Path(__file__).resolve().parent
ENV_PATH = CURRENT_DIR / ".env"

load_dotenv(ENV_PATH)


CYPHER_GENERATION_TEMPLATE = """Task: Generate a Cypher statement to query a Neo4j database.

Use ONLY the provided schema and follow these rules:
- Satellites are connected to products via :PRODUCES.
- Products are connected to parameters via :OBSERVES.
- Products are connected to regions via :COVERS.
- Ocean-related products are identified by parameters where par.category = "ocean".
- Rainfall-related products should be found via the Parameter node, using name/type contains "rain".

Schema:
{schema}

Examples:
# Which products are ocean-related from Oceansat-3?
MATCH (s:Satellite {{name: "Oceansat-3"}})-[:PRODUCES]->(p:Product)-[:OBSERVES]->(par:Parameter)
WHERE par.category = "ocean"
RETURN DISTINCT p.name, p.display_name

# What are the rainfall products from INSAT-3D and where are they available?
MATCH (s:Satellite {{name: "INSAT-3D"}})-[:PRODUCES]->(p:Product)
MATCH (p)-[:OBSERVES]->(par:Parameter)
MATCH (p)-[:COVERS]->(r:Region)
WHERE toLower(par.display_name) CONTAINS "rain"
   OR toLower(par.type) CONTAINS "rain"
RETURN DISTINCT
  p.name AS ProductName,
  p.display_name AS ProductDisplayName,
  r.name AS RegionAvailable

The question is:
{question}"""
QA_TEMPLATE = """You are an assistant answering questions about satellite data products.

You are given:
- A natural language question.
- The Cypher query used to answer it.
- The query results as a list of rows (context). Each row may have fields like:
  - ProductName
  - ProductDisplayName
  - RegionAvailable

Follow these rules:
- If the context list is NOT empty, you should use the context list to answer the question in 1–2 concise sentences.
- If there are multiple products, you may summarize them.
- Do not mention Cypher, Neo4j, or databases in your answer.

Question:
{question}

Query results (context):
{context}

Answer:"""

QA_PROMPT = PromptTemplate(
    input_variables=["question", "context"],
    template=QA_TEMPLATE,
)

CYPHER_GENERATION_PROMPT = PromptTemplate(
    input_variables=["schema", "question"],
    template=CYPHER_GENERATION_TEMPLATE,
)


# ---------------- LAZY NEO4J + LLM + CHAIN ----------------


@lru_cache(maxsize=1)
def get_graph():
    uri = os.getenv("NEO4J_URI")
    username = os.getenv("NEO4J_USERNAME")
    password = os.getenv("NEO4J_PASSWORD")
    if not uri or not username or password is None:
        raise RuntimeError(
            "Neo4j credentials not configured. Set NEO4J_URI, NEO4J_USERNAME, and NEO4J_PASSWORD."
        )
    return Neo4jGraph(
        url=uri.strip(),
        username=username.strip(),
        password=password.strip(),
    )


@lru_cache(maxsize=1)
def get_kg_llm():
    return ChatGoogleGenerativeAI(
        model="gemini-2.5-flash-lite",
        temperature=0,
    )


@lru_cache(maxsize=1)
def get_chain():
    """Return a GraphCypherQAChain with Neo4j.

    SAFETY: allow_dangerous_requests=True is required by LangChain's GraphCypherQAChain
    to execute Cypher queries against the Neo4j database. The chain only runs
    parameterized Cypher generated by the LLM for the known schema. This is
    equivalent to allowing read-write database access and should only be enabled
    with a Neo4j instance that does not contain sensitive data.
    """
    return GraphCypherQAChain.from_llm(
        llm=get_kg_llm(),
        graph=get_graph(),
        verbose=True,
        allow_dangerous_requests=True,
        return_intermediate_steps=True,
        cypher_prompt=CYPHER_GENERATION_PROMPT,
        qa_prompt=QA_PROMPT,
    )


# ---------------- PUBLIC HELPER ----------------

def ask_kg(question: str, history: list | None = None) -> Dict[str, Any]:
    history_prefix = ""
    if history:
        last = history[-6:]  # keep it short
        lines = []
        for msg in last:
            prefix = "User:" if msg["role"] == "user" else "Assistant:"
            lines.append(f"{prefix} {msg['content']}")
        history_prefix = "\n".join(lines) + "\n\n"

    # 2) Feed a history-aware question into the chain
    history_aware_question = history_prefix + f"User's current question: {question}"
    result = get_chain().invoke({"query": history_aware_question})
    steps = result.get("intermediate_steps", [])

    cypher = ""
    rows: Any = []

    if steps:
        cypher = steps[0].get("query", "")
        if len(steps) > 1:
            rows = steps[1].get("context", [])

    return {
        "answer": result.get("result", ""),
        "cypher": cypher,
        "rows": rows,
    }



# ---------------- DEV MAIN ----------------

if __name__ == "__main__":
    for q in [
        "Where is INSAT-3D rainfall data?",
        "What are the rainfall products from INSAT-3D and where are they available?",
        "Which products are ocean-related from Oceansat-3?",
    ]:
        out = ask_kg(q)
        print("\nQ:", q)
        print("Answer:", out["answer"])
        print("Cypher:", out["cypher"])
        print("Rows:", out["rows"])
